SiteChecker.UI/Models/ErrorViewModel.cs
namespace SiteChecker.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SiteChecker.UI/ViewModels/DashboardViewModel.cs
namespace SiteChecker.UI.ViewModels
{
    public class DashboardViewModel
    {
        public List<WebsiteInfoDTO>? websiteInfoDTOs {  get; set; }
    }
}

SiteChecker.UI/ViewModels/WebsiteInfoDTO.cs
namespace SiteChecker.UI.ViewModels
{
    public class WebsiteInfoDTO
    {
        public required string WebsiteUrl { get; set; }
        public int MonitoringIntervalSeconds { get; set; }
        public bool IsUp { get; set; }
        public DateTime? LastCheckedAt { get; set; }
    }
}

SiteChecker.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SiteChecker.UI.Models;
using System.Diagnostics;

namespace SiteChecker.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SiteChecker.UI/Controllers/WebsiteInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebsiteMinion.Contexts;
using WebsiteMinion.Models;

namespace SiteChecker.UI.Controllers
{
    public class WebsiteInfoController : Controller
    {
        private readonly Serilog.ILogger _logger;
        private readonly WebsiteDbContext _context;

        public WebsiteInfoController(Serilog.ILogger logger, WebsiteDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        // GET: WebsiteInfo
        public async Task<IActionResult> Index()
        {
            _logger.Information("Getting all website info");
            return View(await _context.Websiteinfos.ToListAsync());
        }

        // GET: WebsiteInfo/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            _logger.Information("Getting website info details for {id}", id);
            if (id == null)
            {
                return NotFound();
            }

            var websiteInfo = await _context.Websiteinfos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (websiteInfo == null)
            {
                return NotFound();
            }

            return View(websiteInfo);
        }

        // GET: WebsiteInfo/Create
        public IActionResult Create()
        {
            _logger.Information("Creating new website info");
            return View();
        }

        // POST: WebsiteInfo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WebsiteUrl,RegisteredAt,MonitoringEnabled,LastCheckedAt,MonitoringIntervalSeconds,Id,CreatedBy,CreatedAt,ModifiedBy,ModifiedAt")] WebsiteInfo websiteInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(websiteInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(websiteInfo);
        }

        // GET: WebsiteInfo/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var websiteInfo = await _context.Websiteinfos.FindAsync(id);
            if (websiteInfo == null)
            {
                return NotFound();
            }
            return View(websiteInfo);
        }

        // POST: WebsiteInfo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("WebsiteUrl,RegisteredAt,MonitoringEnabled,LastCheckedAt,MonitoringIntervalSeconds,Id,CreatedBy,CreatedAt,ModifiedBy,ModifiedAt")] WebsiteInfo websiteInfo)
        {
            _logger.Information("Editing website info for {id} {@websiteInfo}", id, websiteInfo);
            if (id != websiteInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(websiteInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WebsiteInfoExists(websiteInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(websiteInfo);
        }

        // GET: WebsiteInfo/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            _logger.Information("Deleting website info for {id}", id);
            if (id == null)
            {
                return NotFound();
            }

            var websiteInfo = await _context.Websiteinfos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (websiteInfo == null)
            {
                return NotFound();
            }

            return View(websiteInfo);
        }

        // POST: WebsiteInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            _logger.Information("Deleting website info for {id}", id);
            var websiteInfo = await _context.Websiteinfos.FindAsync(id);
            if (websiteInfo != null)
            {
                _context.Websiteinfos.Remove(websiteInfo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WebsiteInfoExists(long id)
        {
            return _context.Websiteinfos.Any(e => e.Id == id);
        }
    }
}

SiteChecker.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SiteChecker.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteChecker.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SiteChecker.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiteChecker.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WebsiteInfo" asp-action="Index">WebsiteInfo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SiteChecker.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SiteChecker.UI/Views/WebsiteInfo/Create.cshtml
@model WebsiteMinion.Models.WebsiteInfo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WebsiteInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WebsiteUrl" class="control-label"></label>
                <input asp-for="WebsiteUrl" class="form-control" />
                <span asp-validation-for="WebsiteUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisteredAt" class="control-label"></label>
                <input asp-for="RegisteredAt" class="form-control" />
                <span asp-validation-for="RegisteredAt" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MonitoringEnabled" /> @Html.DisplayNameFor(model => model.MonitoringEnabled)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="LastCheckedAt" class="control-label"></label>
                <input asp-for="LastCheckedAt" class="form-control" />
                <span asp-validation-for="LastCheckedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonitoringIntervalSeconds" class="control-label"></label>
                <input asp-for="MonitoringIntervalSeconds" class="form-control" />
                <span asp-validation-for="MonitoringIntervalSeconds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedAt" class="control-label"></label>
                <input asp-for="ModifiedAt" class="form-control" />
                <span asp-validation-for="ModifiedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SiteChecker.UI/Views/WebsiteInfo/Delete.cshtml
@model WebsiteMinion.Models.WebsiteInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WebsiteInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebsiteUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisteredAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisteredAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonitoringEnabled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonitoringEnabled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastCheckedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastCheckedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonitoringIntervalSeconds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonitoringIntervalSeconds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SiteChecker.UI/Views/WebsiteInfo/Details.cshtml
@model WebsiteMinion.Models.WebsiteInfo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WebsiteInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WebsiteUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WebsiteUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisteredAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisteredAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonitoringEnabled)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonitoringEnabled)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastCheckedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastCheckedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonitoringIntervalSeconds)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MonitoringIntervalSeconds)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModifiedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SiteChecker.UI/Views/WebsiteInfo/Edit.cshtml
@model WebsiteMinion.Models.WebsiteInfo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WebsiteInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="WebsiteUrl" class="control-label"></label>
                <input asp-for="WebsiteUrl" class="form-control" />
                <span asp-validation-for="WebsiteUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisteredAt" class="control-label"></label>
                <input asp-for="RegisteredAt" class="form-control" />
                <span asp-validation-for="RegisteredAt" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="MonitoringEnabled" /> @Html.DisplayNameFor(model => model.MonitoringEnabled)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="LastCheckedAt" class="control-label"></label>
                <input asp-for="LastCheckedAt" class="form-control" />
                <span asp-validation-for="LastCheckedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MonitoringIntervalSeconds" class="control-label"></label>
                <input asp-for="MonitoringIntervalSeconds" class="form-control" />
                <span asp-validation-for="MonitoringIntervalSeconds" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedBy" class="control-label"></label>
                <input asp-for="ModifiedBy" class="form-control" />
                <span asp-validation-for="ModifiedBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModifiedAt" class="control-label"></label>
                <input asp-for="ModifiedAt" class="form-control" />
                <span asp-validation-for="ModifiedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SiteChecker.UI/Views/WebsiteInfo/Index.cshtml
@model IEnumerable<WebsiteMinion.Models.WebsiteInfo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.WebsiteUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegisteredAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonitoringEnabled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastCheckedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MonitoringIntervalSeconds)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedAt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.WebsiteUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegisteredAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonitoringEnabled)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastCheckedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MonitoringIntervalSeconds)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedAt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>